"""ADAMS View command file writer.

Generates .cmd files compatible with MSC ADAMS View.
Output matches VBA implementation (Inventor2AdamsView.ivb).

Coordinate conventions:
    - Position: millimeters (converted from IR meters)
    - Rotation: ZXZ Euler angles in degrees
    - Density: kg/mm^3 (converted from IR kg/m^3)
    - Inertia: kg*mm^2 (converted from IR kg*m^2)

Output structure:
    1. Header comment
    2. Material definitions (material create commands)
    3. Rigid body definitions (part create rigid_body commands)
    4. Geometry imports (file geometry read commands)
"""

import io
from pathlib import Path
from typing import Optional

from inventor_exporter.core.rotation import EulerConvention, rotation_to_euler
from inventor_exporter.model import AssemblyModel, Body, Material
from inventor_exporter.writers.registry import WriterRegistry


@WriterRegistry.register("adams")
class AdamsWriter:
    """ADAMS View command file writer.

    Generates .cmd files compatible with MSC ADAMS View.
    Output format matches VBA implementation for validation.

    Attributes:
        format_name: "adams"
        file_extension: ".cmd"
    """

    format_name: str = "adams"
    file_extension: str = ".cmd"

    def __init__(self, model_name: Optional[str] = None):
        """Initialize ADAMS writer.

        Args:
            model_name: ADAMS model name override. If None, derives from
                assembly name with 'model_' prefix.
        """
        self._model_name_override = model_name

    def write(self, model: AssemblyModel, output_path: Path) -> None:
        """Write assembly model to ADAMS View command file.

        Args:
            model: AssemblyModel to export.
            output_path: Destination .cmd file path.

        Raises:
            ValueError: If model validation fails.
        """
        errors = model.validate()
        if errors:
            raise ValueError(
                "Model validation failed:\n" + "\n".join(f"  - {e}" for e in errors)
            )

        model_name = self._get_model_name(model)
        content = self._generate_content(model, model_name)
        output_path.write_text(content, encoding="utf-8")

    def _get_model_name(self, model: AssemblyModel) -> str:
        """Get ADAMS model name from override or assembly name."""
        if self._model_name_override:
            return self._model_name_override
        name = model.name.replace(" ", "_").replace("-", "_")
        if not name.startswith("model_"):
            name = f"model_{name}"
        return name

    def _generate_content(self, model: AssemblyModel, model_name: str) -> str:
        """Generate complete command file content."""
        output = io.StringIO()

        # Header comment
        output.write("! ADAMS View command file generated by inventor-exporter\n")
        output.write(f"! Assembly: {model.name}\n")
        output.write(f"! Model: {model_name}\n")
        output.write("!\n\n")

        # Materials section
        output.write("! === Materials ===\n")
        for material in model.materials:
            output.write(self._generate_material(material, model_name))
            output.write("\n")

        # Rigid bodies section
        output.write("! === Rigid Bodies ===\n")
        for body in model.bodies:
            output.write(self._generate_rigid_body(body, model_name))
            output.write("\n")

        # Geometry section
        output.write("! === Geometry ===\n")
        for body in model.bodies:
            if body.geometry_file:
                output.write(self._generate_geometry(body, model_name))
                output.write("\n")

        return output.getvalue()

    def _generate_material(self, material: Material, model_name: str) -> str:
        """Generate material create command.

        Converts density from kg/m^3 to kg/mm^3 for ADAMS.
        """
        # kg/m^3 * 1e-9 = kg/mm^3
        density_kg_mm3 = material.density * 1e-9

        # Use defaults if not specified (matching VBA behavior)
        youngs = material.youngs_modulus if material.youngs_modulus else 207000.0
        poissons = material.poissons_ratio if material.poissons_ratio else 0.29

        return (
            f"material create  &\n"
            f"   material_name = .{model_name}.{material.name}  &\n"
            f"   youngs_modulus = {youngs:.6e}  &\n"
            f"   poissons_ratio = {poissons}  &\n"
            f"   density = {density_kg_mm3:.15e}\n"
        )

    def _generate_rigid_body(self, body: Body, model_name: str) -> str:
        """Generate rigid body commands.

        Converts position from meters to mm.
        Converts rotation to ZXZ Euler angles in degrees.
        """
        lines = []

        # Convert position from meters to mm
        pos_mm = body.transform.position * 1000.0

        # Get ZXZ Euler angles in degrees
        angles = rotation_to_euler(
            body.transform.rotation, EulerConvention.ADAMS_ZXZ, degrees=True
        )

        # Part creation with name and position
        lines.append("part create rigid_body name_and_position  &")
        lines.append(f"   part_name = .{model_name}.{body.name}  &")
        lines.append(
            f"   location = {pos_mm[0]:.6f}, {pos_mm[1]:.6f}, {pos_mm[2]:.6f}  &"
        )
        lines.append(
            f"   orientation = {angles[0]:.6f}d, {angles[1]:.6f}d, {angles[2]:.6f}d"
        )
        lines.append("")

        # Mass properties (if inertia present)
        if body.inertia and body.material_name:
            lines.extend(self._generate_mass_properties(body, model_name))

        return "\n".join(lines)

    def _generate_mass_properties(self, body: Body, model_name: str) -> list[str]:
        """Generate mass properties command for body with inertia.

        Converts inertia tensor from kg*m^2 to kg*mm^2.
        """
        lines = []
        inertia = body.inertia

        # Inertia tensor: kg*m^2 * (1000 mm/m)^2 = kg*mm^2 * 1e6
        I = inertia.inertia_tensor * 1e6

        lines.append("part create rigid_body mass_properties  &")
        lines.append(f"   part_name = .{model_name}.{body.name}  &")
        lines.append(f"   material_type = .{model_name}.{body.material_name}  &")
        lines.append(f"   mass = {inertia.mass:.6f}  &")
        lines.append(f"   ixx = {I[0, 0]:.6e}  &")
        lines.append(f"   iyy = {I[1, 1]:.6e}  &")
        lines.append(f"   izz = {I[2, 2]:.6e}  &")
        lines.append(f"   ixy = {I[0, 1]:.6e}  &")
        lines.append(f"   izx = {I[2, 0]:.6e}  &")
        lines.append(f"   iyz = {I[1, 2]:.6e}")
        lines.append("")

        return lines

    def _generate_geometry(self, body: Body, model_name: str) -> str:
        """Generate geometry import commands."""
        if body.geometry_file is None:
            return ""

        step_file = body.geometry_file.name

        lines = []
        lines.append("file geometry read  &")
        lines.append("   type_of_geometry = stp  &")
        lines.append(f"   file_name = {step_file}  &")
        lines.append(f"   part_name = .{model_name}.{body.name}")
        lines.append("")

        return "\n".join(lines)
