"""URDF (Unified Robot Description Format) writer.

Generates .urdf files compatible with ROS (Robot Operating System).
URDF is the standard format for robot descriptions in the ROS ecosystem.

Coordinate conventions:
    - Position: meters (no conversion needed from IR)
    - Rotation: RPY angles in radians (roll-pitch-yaw = extrinsic XYZ = intrinsic ZYX)
    - Mesh format: STL files in meshes/ subdirectory

Output structure:
    1. XML declaration
    2. Robot root element with name attribute
    3. Material definitions (defined once, referenced by name)
    4. Virtual base_link at world origin (no geometry)
    5. Physical links with visual, collision, and inertial elements
    6. Fixed joints connecting each physical link to base_link

The base_link convention is standard for robot descriptions - it provides
a fixed reference frame at the world origin that all other bodies attach to.
"""

import logging
from pathlib import Path
from typing import Optional

from lxml import etree

from inventor_exporter.core.rotation import EulerConvention, rotation_to_euler
from inventor_exporter.model import AssemblyModel, Body, Material
from inventor_exporter.writers.mesh_converter import MeshConverter
from inventor_exporter.writers.registry import WriterRegistry

logger = logging.getLogger(__name__)


# Default material colors (RGBA) based on common material types
# Used when material doesn't have explicit color
DEFAULT_COLORS = {
    "steel": "0.7 0.7 0.7 1.0",
    "aluminum": "0.8 0.8 0.85 1.0",
    "plastic": "0.3 0.3 0.3 1.0",
    "rubber": "0.2 0.2 0.2 1.0",
    "default": "0.6 0.6 0.6 1.0",
}


@WriterRegistry.register("urdf")
class URDFWriter:
    """URDF format writer for ROS-compatible robot descriptions.

    Generates .urdf files with proper XML structure including:
    - Material definitions at robot level
    - Virtual base_link at world origin
    - Physical links with visual, collision, and inertial elements
    - Fixed joints connecting bodies to base_link

    Attributes:
        format_name: "urdf"
        file_extension: ".urdf"
    """

    format_name: str = "urdf"
    file_extension: str = ".urdf"

    def __init__(self, mesh_tolerance: float = 0.1):
        """Initialize URDF writer.

        Args:
            mesh_tolerance: Linear deflection tolerance for STEP to STL
                conversion. Lower values produce finer meshes. Default 0.1.
        """
        self._mesh_tolerance = mesh_tolerance

    def write(self, model: AssemblyModel, output_path: Path) -> None:
        """Write assembly model to URDF file.

        Args:
            model: AssemblyModel to export.
            output_path: Destination .urdf file path.

        Raises:
            ValueError: If model validation fails.
        """
        errors = model.validate()
        if errors:
            raise ValueError(
                "Model validation failed:\n" + "\n".join(f"  - {e}" for e in errors)
            )

        # Set up mesh converter for STEP -> STL conversion
        output_dir = output_path.parent
        mesh_converter = MeshConverter(output_dir, mesh_subdir="meshes")

        # Build XML tree
        robot = self._build_robot_element(model, mesh_converter)

        # Write to file with pretty printing and XML declaration
        tree = etree.ElementTree(robot)
        tree.write(
            str(output_path),
            encoding="utf-8",
            xml_declaration=True,
            pretty_print=True,
        )

        logger.info("Wrote URDF to %s", output_path)

    def _build_robot_element(
        self, model: AssemblyModel, mesh_converter: MeshConverter
    ) -> etree._Element:
        """Build the complete robot XML element.

        Args:
            model: AssemblyModel to convert.
            mesh_converter: MeshConverter for geometry conversion.

        Returns:
            Root <robot> element with all children.
        """
        # Create root element
        robot = etree.Element("robot", name=model.name)

        # Add header comment
        robot.append(
            etree.Comment(
                " URDF generated by inventor-exporter "
            )
        )
        robot.append(
            etree.Comment(
                f" Assembly: {model.name} "
            )
        )
        robot.append(
            etree.Comment(
                " Units: meters (position), radians (rotation) "
            )
        )

        # === Materials Section ===
        robot.append(etree.Comment(" === Materials === "))
        for material in model.materials:
            self._add_material(robot, material)

        # === Base Link (virtual frame at world origin) ===
        robot.append(etree.Comment(" === Base Link (world origin) === "))
        base_link = etree.SubElement(robot, "link", name="base_link")
        base_link.append(etree.Comment(" Virtual frame - no geometry "))

        # === Physical Links ===
        robot.append(etree.Comment(" === Physical Links === "))
        for body in model.bodies:
            self._add_link(robot, body, model, mesh_converter)

        # === Fixed Joints ===
        robot.append(etree.Comment(" === Fixed Joints === "))
        for body in model.bodies:
            self._add_fixed_joint(robot, body)

        return robot

    def _add_material(self, parent: etree._Element, material: Material) -> None:
        """Add material definition element.

        Args:
            parent: Parent element to add to.
            material: Material to define.
        """
        mat_elem = etree.SubElement(parent, "material", name=material.name)

        # Determine color based on material name or use default
        color = self._get_material_color(material)
        etree.SubElement(mat_elem, "color", rgba=color)

    def _get_material_color(self, material: Material) -> str:
        """Get RGBA color string for material.

        Uses material name to determine color, falling back to default.

        Args:
            material: Material to get color for.

        Returns:
            RGBA color string (e.g., "0.7 0.7 0.7 1.0").
        """
        name_lower = material.name.lower()

        # Check for known material types
        for material_type, color in DEFAULT_COLORS.items():
            if material_type in name_lower:
                return color

        # Fallback to default gray
        return DEFAULT_COLORS["default"]

    def _add_link(
        self,
        parent: etree._Element,
        body: Body,
        model: AssemblyModel,
        mesh_converter: MeshConverter,
    ) -> None:
        """Add link element for a body.

        Args:
            parent: Parent element to add to.
            body: Body to create link for.
            model: AssemblyModel (for material lookup).
            mesh_converter: MeshConverter for geometry.
        """
        link = etree.SubElement(parent, "link", name=body.name)

        # Inertial element (if body has inertia)
        if body.inertia is not None:
            self._add_inertial(link, body)

        # Visual element (if body has geometry)
        mesh_path: Optional[Path] = None
        if body.geometry_file is not None:
            try:
                mesh_path = mesh_converter.convert(
                    body.geometry_file,
                    body.name,
                    tolerance=self._mesh_tolerance,
                )
            except Exception as e:
                logger.warning(
                    "Failed to convert mesh for %s: %s", body.name, e
                )
                mesh_path = None

        if mesh_path is not None:
            self._add_visual(link, body, mesh_path)
            self._add_collision(link, body, mesh_path)

    def _add_inertial(self, link: etree._Element, body: Body) -> None:
        """Add inertial element to link.

        Args:
            link: Parent link element.
            body: Body with inertia data.
        """
        if body.inertia is None:
            return

        inertial = etree.SubElement(link, "inertial")

        # Origin at center of mass (relative to link frame)
        # For URDF, the inertial origin is the CoM position in link frame
        com = body.inertia.center_of_mass
        etree.SubElement(
            inertial,
            "origin",
            xyz=f"{com[0]:.6g} {com[1]:.6g} {com[2]:.6g}",
            rpy="0 0 0",
        )

        # Mass
        etree.SubElement(inertial, "mass", value=f"{body.inertia.mass:.6g}")

        # Inertia tensor (at center of mass)
        I = body.inertia.inertia_tensor
        etree.SubElement(
            inertial,
            "inertia",
            ixx=f"{I[0, 0]:.6g}",
            ixy=f"{I[0, 1]:.6g}",
            ixz=f"{I[0, 2]:.6g}",
            iyy=f"{I[1, 1]:.6g}",
            iyz=f"{I[1, 2]:.6g}",
            izz=f"{I[2, 2]:.6g}",
        )

    def _add_visual(
        self, link: etree._Element, body: Body, mesh_path: Path
    ) -> None:
        """Add visual element to link.

        Args:
            link: Parent link element.
            body: Body for material reference.
            mesh_path: Relative path to mesh file.
        """
        visual = etree.SubElement(link, "visual")

        # Origin at link frame origin (mesh is already in link frame)
        etree.SubElement(visual, "origin", xyz="0 0 0", rpy="0 0 0")

        # Geometry with mesh reference
        geometry = etree.SubElement(visual, "geometry")
        # Use forward slashes for cross-platform compatibility in URDF
        mesh_filename = str(mesh_path).replace("\\", "/")
        etree.SubElement(geometry, "mesh", filename=mesh_filename)

        # Material reference (if body has material)
        if body.material_name:
            etree.SubElement(visual, "material", name=body.material_name)

    def _add_collision(
        self, link: etree._Element, body: Body, mesh_path: Path
    ) -> None:
        """Add collision element to link.

        Collision geometry matches visual geometry (same mesh).

        Args:
            link: Parent link element.
            body: Body (for consistency).
            mesh_path: Relative path to mesh file.
        """
        collision = etree.SubElement(link, "collision")

        # Origin at link frame origin
        etree.SubElement(collision, "origin", xyz="0 0 0", rpy="0 0 0")

        # Geometry with same mesh as visual
        geometry = etree.SubElement(collision, "geometry")
        mesh_filename = str(mesh_path).replace("\\", "/")
        etree.SubElement(geometry, "mesh", filename=mesh_filename)

    def _add_fixed_joint(self, parent: etree._Element, body: Body) -> None:
        """Add fixed joint connecting body to base_link.

        Args:
            parent: Parent element to add to.
            body: Body to connect.
        """
        joint = etree.SubElement(
            parent,
            "joint",
            name=f"{body.name}_joint",
            type="fixed",
        )

        # Parent is always base_link
        etree.SubElement(joint, "parent", link="base_link")

        # Child is this body's link
        etree.SubElement(joint, "child", link=body.name)

        # Origin: body position and orientation relative to base_link (world)
        pos = body.transform.position
        rpy = rotation_to_euler(
            body.transform.rotation,
            EulerConvention.URDF_RPY,
            degrees=False,
        )

        etree.SubElement(
            joint,
            "origin",
            xyz=f"{pos[0]:.6g} {pos[1]:.6g} {pos[2]:.6g}",
            rpy=f"{rpy[0]:.6g} {rpy[1]:.6g} {rpy[2]:.6g}",
        )
