"""URDF (Unified Robot Description Format) writer.

Generates .urdf files compatible with ROS (Robot Operating System).

Coordinate conventions:
    - Position: meters (no conversion needed from IR)
    - Rotation: RPY angles in radians (roll-pitch-yaw = extrinsic XYZ = intrinsic ZYX)
    - Mesh format: STL files in meshes/ subdirectory

Structure:
    - Material definitions (defined once, referenced by name)
    - Virtual base_link at world origin
    - Physical links with visual, collision, and inertial elements
    - Rigid groups: parts connected by rigid joints are merged into one link
    - Kinematic tree: built via BFS spanning tree with proper joints
    - Closed loops: handled via <gazebo> extension tags (SDF joints)
"""

import logging
from pathlib import Path
from typing import Optional

import numpy as np
from lxml import etree

from inventor_exporter.core.rotation import EulerConvention, rotation_to_euler
from inventor_exporter.model import AssemblyModel, Body, Material
from inventor_exporter.model.constraint import ConstraintInfo
from inventor_exporter.model.kinematic_tree import (
    KinematicTree,
    classify_joints,
    get_joint_origin_in_child_frame,
)
from inventor_exporter.writers.mesh_converter import MeshConverter
from inventor_exporter.writers.registry import WriterRegistry

logger = logging.getLogger(__name__)

DEFAULT_COLORS = {
    "steel": "0.7 0.7 0.7 1.0",
    "aluminum": "0.8 0.8 0.85 1.0",
    "plastic": "0.3 0.3 0.3 1.0",
    "rubber": "0.2 0.2 0.2 1.0",
    "default": "0.6 0.6 0.6 1.0",
}

# Inventor joint type -> URDF joint type
_URDF_JOINT_TYPE = {
    "rotational_joint": "revolute",
    "slider_joint": "prismatic",
    "cylindrical_joint": "revolute",
    "planar_joint": "planar",
    "ball_joint": "fixed",  # URDF has no ball joint
}


def _format_xyz(position) -> str:
    return f"{position[0]:.6g} {position[1]:.6g} {position[2]:.6g}"


def _format_rpy(rotation) -> str:
    rpy = rotation_to_euler(rotation, EulerConvention.URDF_RPY, degrees=False)
    return f"{rpy[0]:.6g} {rpy[1]:.6g} {rpy[2]:.6g}"


@WriterRegistry.register("urdf")
class URDFWriter:
    """URDF format writer with kinematic tree, rigid-group merging, and
    closed-loop support via Gazebo extensions."""

    format_name: str = "urdf"
    file_extension: str = ".urdf"

    def __init__(
        self,
        mesh_tolerance: float = 0.1,
        collision_mode: str = "mesh",
    ):
        self._mesh_tolerance = mesh_tolerance
        self._collision_mode = collision_mode

    def write(self, model: AssemblyModel, output_path: Path) -> None:
        errors = model.validate()
        if errors:
            raise ValueError(
                "Model validation failed:\n" + "\n".join(f"  - {e}" for e in errors)
            )

        output_dir = output_path.parent
        mesh_converter = MeshConverter(
            output_dir,
            mesh_subdir="meshes",
            collision_mode=self._collision_mode,
        )

        robot = self._build_robot_element(model, mesh_converter)

        tree = etree.ElementTree(robot)
        tree.write(
            str(output_path),
            encoding="utf-8",
            xml_declaration=True,
            pretty_print=True,
        )
        logger.info("Wrote URDF to %s", output_path)

    def _build_robot_element(
        self, model: AssemblyModel, mesh_converter: MeshConverter
    ) -> etree._Element:
        robot = etree.Element("robot", name=model.name)

        robot.append(etree.Comment(" URDF generated by inventor-exporter "))
        robot.append(etree.Comment(f" Assembly: {model.name} "))
        robot.append(etree.Comment(" Units: meters (position), radians (rotation) "))

        # Constraint / joint metadata
        if model.constraints:
            self._add_constraint_comments(robot, model)

        # Materials
        robot.append(etree.Comment(" === Materials === "))
        for material in model.materials:
            self._add_material(robot, material)

        # Build kinematic tree
        groups = model.rigid_groups()
        ktree = classify_joints(
            [b.name for b in model.bodies],
            model.constraints,
            ground=model.ground_body,
            rigid_groups=groups,
        )

        # Base link
        robot.append(etree.Comment(" === Base Link (world origin) === "))
        base_link = etree.SubElement(robot, "link", name="base_link")
        base_link.append(etree.Comment(" Virtual frame - no geometry "))

        # Emit links — all links are top-level (URDF is flat)
        robot.append(etree.Comment(" === Physical Links === "))
        emitted: set[str] = set()
        # Map from link name -> Body (primary body for that link)
        link_primaries: dict[str, Body] = {}

        for rep, members in groups.items():
            if len(members) == 1:
                body = model.get_body(members[0])
                if body is not None:
                    self._add_link(robot, body, model, mesh_converter)
                    link_primaries[body.name] = body
            else:
                name = self._add_rigid_group_link(
                    robot, members, model, mesh_converter
                )
                primary = model.get_body(members[0])
                if primary is not None:
                    link_primaries[name] = primary
            emitted.update(members)

        # Safety net
        for body in model.bodies:
            if body.name not in emitted:
                self._add_link(robot, body, model, mesh_converter)
                link_primaries[body.name] = body

        # Resolve link name for a body (may be in a rigid group)
        def _link_name_for(body_name: str) -> str:
            for rep, members in groups.items():
                if body_name in members and len(members) > 1:
                    return "_".join(members[:2]) + "_group"
            return body_name

        # Emit joints
        robot.append(etree.Comment(" === Joints === "))

        # Root bodies: fixed joints to base_link
        for root_name in ktree.root_bodies:
            root_body = model.get_body(root_name)
            if root_body is None:
                continue
            lname = _link_name_for(root_name)
            # Skip if rigid group member is not the representative
            if lname not in link_primaries:
                continue
            self._add_fixed_joint(robot, lname, root_body)

        # Tree joints: kinematic joints between parent and child
        for child_name, parent_name in ktree.parent_of.items():
            constraint = ktree.joint_for[child_name]
            child_body = model.get_body(child_name)
            parent_body = model.get_body(parent_name)
            if child_body is None or parent_body is None:
                continue

            child_link = _link_name_for(child_name)
            parent_link = _link_name_for(parent_name)

            is_flipped = child_name in ktree.flipped
            self._add_kinematic_joint(
                robot, child_link, parent_link,
                constraint, child_body, parent_body, is_flipped,
            )

        # Cut joints: Gazebo extensions for loop closure
        if ktree.cut_joints:
            self._add_gazebo_loop_joints(robot, ktree, model, _link_name_for)

        # Disable collisions between connected links when CoACD is active
        if self._collision_mode == "coacd":
            self._add_collision_filters(robot, ktree, groups, _link_name_for)

        return robot

    # ------------------------------------------------------------------
    # Kinematic joint
    # ------------------------------------------------------------------

    def _add_kinematic_joint(
        self,
        parent_elem: etree._Element,
        child_link: str,
        parent_link: str,
        constraint: ConstraintInfo,
        child_body: Body,
        parent_body: Body,
        is_flipped: bool,
    ) -> None:
        """Add a proper kinematic <joint> between parent and child links."""
        urdf_type = _URDF_JOINT_TYPE.get(constraint.type, "fixed")
        joint_name = constraint.name.replace(":", "_") if constraint.name else (
            f"{parent_link}_to_{child_link}_joint"
        )

        if constraint.type == "ball_joint":
            logger.warning(
                "URDF does not support ball joints. Joint '%s' exported as "
                "fixed. Consider using SDF format instead.",
                joint_name,
            )

        joint = etree.SubElement(
            parent_elem, "joint", name=joint_name, type=urdf_type,
        )
        etree.SubElement(joint, "parent", link=parent_link)
        etree.SubElement(joint, "child", link=child_link)

        # Origin: transform from parent frame to child frame
        rel = child_body.transform.relative_to(parent_body.transform)
        etree.SubElement(
            joint, "origin",
            xyz=_format_xyz(rel.position),
            rpy=_format_rpy(rel.rotation),
        )

        # Axis (in child frame)
        if constraint.axis is not None and urdf_type in ("revolute", "prismatic", "planar"):
            axis_world = np.array(constraint.axis)
            axis_local = child_body.transform.rotation.T @ axis_world
            norm = np.linalg.norm(axis_local)
            if norm > 1e-12:
                axis_local = axis_local / norm
            etree.SubElement(
                joint, "axis",
                xyz=f"{axis_local[0]:.6g} {axis_local[1]:.6g} {axis_local[2]:.6g}",
            )

        # Limits
        if constraint.limits is not None and urdf_type in ("revolute", "prismatic"):
            etree.SubElement(
                joint, "limit",
                lower=f"{constraint.limits[0]:.6g}",
                upper=f"{constraint.limits[1]:.6g}",
                effort="100",
                velocity="1",
            )
        elif urdf_type == "revolute":
            # Revolute joints require limits in URDF; use defaults
            etree.SubElement(
                joint, "limit",
                lower="-3.14159",
                upper="3.14159",
                effort="100",
                velocity="1",
            )

    # ------------------------------------------------------------------
    # Gazebo loop closure extensions
    # ------------------------------------------------------------------

    def _add_gazebo_loop_joints(
        self,
        robot: etree._Element,
        ktree: KinematicTree,
        model: AssemblyModel,
        link_name_fn,
    ) -> None:
        """Add <gazebo> extension tags with SDF joints for loop closure."""
        robot.append(etree.Comment(
            " === Loop Closure (Gazebo extension) === "
        ))
        robot.append(etree.Comment(
            " URDF does not support closed kinematic chains. "
            "These joints are included as Gazebo extensions "
            "and will only work when loaded in Gazebo (which "
            "converts URDF to SDF). "
        ))

        for i, cj in enumerate(ktree.cut_joints):
            body1_name = cj.occurrence_one.replace(":", "_").replace(" ", "_")
            body2_name = cj.occurrence_two.replace(":", "_").replace(" ", "_")
            link1 = link_name_fn(body1_name)
            link2 = link_name_fn(body2_name)

            b1 = model.get_body(body1_name)
            b2 = model.get_body(body2_name)
            if b1 is None or b2 is None:
                continue

            joint_name = cj.name.replace(":", "_") if cj.name else f"loop_{i}"
            sdf_type = _URDF_JOINT_TYPE.get(cj.type, "fixed")
            if sdf_type == "fixed" and cj.type == "ball_joint":
                sdf_type = "ball"

            gazebo = etree.SubElement(robot, "gazebo")
            joint = etree.SubElement(
                gazebo, "joint", name=joint_name, type=sdf_type,
            )
            parent_el = etree.SubElement(joint, "parent")
            parent_el.text = link1
            child_el = etree.SubElement(joint, "child")
            child_el.text = link2

            if cj.axis is not None and sdf_type in ("revolute", "prismatic"):
                axis_el = etree.SubElement(joint, "axis")
                xyz_el = etree.SubElement(axis_el, "xyz")
                xyz_el.text = (
                    f"{cj.axis[0]:.6g} {cj.axis[1]:.6g} {cj.axis[2]:.6g}"
                )

    # ------------------------------------------------------------------
    # Collision filtering for connected links
    # ------------------------------------------------------------------

    def _add_collision_filters(
        self,
        robot: etree._Element,
        ktree: KinematicTree,
        groups: dict[str, list[str]],
        link_name_fn,
    ) -> None:
        """Add <gazebo> tags to disable collisions between connected links.

        Most URDF consumers auto-filter adjacent link collisions, but
        Gazebo requires explicit ``<disable_collisions>`` when using
        convex collision meshes that extend beyond the joint interface.
        """
        # Collect unique link pairs
        pairs: set[tuple[str, str]] = set()
        for child_name, parent_name in ktree.parent_of.items():
            l1 = link_name_fn(child_name)
            l2 = link_name_fn(parent_name)
            if l1 == l2:
                continue
            pair = (min(l1, l2), max(l1, l2))
            pairs.add(pair)
        for cj in ktree.cut_joints:
            b1 = cj.occurrence_one.replace(":", "_").replace(" ", "_")
            b2 = cj.occurrence_two.replace(":", "_").replace(" ", "_")
            l1 = link_name_fn(b1)
            l2 = link_name_fn(b2)
            if l1 != l2:
                pair = (min(l1, l2), max(l1, l2))
                pairs.add(pair)

        if not pairs:
            return

        robot.append(etree.Comment(
            " === Collision Filtering (connected links) === "
        ))
        for l1, l2 in sorted(pairs):
            gazebo = etree.SubElement(robot, "gazebo", reference=l1)
            etree.SubElement(
                gazebo, "disable_collisions", link=l2
            ).text = "true"

    # ------------------------------------------------------------------
    # Constraint comments
    # ------------------------------------------------------------------

    def _add_constraint_comments(
        self, parent: etree._Element, model: AssemblyModel
    ) -> None:
        lines = [" Assembly constraints and joints:"]
        for c in model.constraints:
            parts = [f"  {c.type}: {c.occurrence_one} <-> {c.occurrence_two}"]
            if c.name:
                parts.append(f"name={c.name}")
            if c.offset is not None:
                parts.append(f"offset={c.offset:.4f}m")
            if c.angle is not None:
                parts.append(f"angle={c.angle:.4f}rad")
            if c.axis is not None:
                parts.append(f"axis=({c.axis[0]:.3f},{c.axis[1]:.3f},{c.axis[2]:.3f})")
            if c.origin is not None:
                parts.append(
                    f"origin=({c.origin[0]:.4f},{c.origin[1]:.4f},{c.origin[2]:.4f})m"
                )
            if c.limits is not None:
                parts.append(f"limits=({c.limits[0]:.4f},{c.limits[1]:.4f})")
            if c.is_rigid:
                parts.append("[RIGID]")
            lines.append(", ".join(parts))
        lines.append("")
        parent.append(etree.Comment("\n".join(lines)))

    # ------------------------------------------------------------------
    # Materials
    # ------------------------------------------------------------------

    def _add_material(self, parent: etree._Element, material: Material) -> None:
        mat_elem = etree.SubElement(parent, "material", name=material.name)
        color = self._get_material_color(material)
        etree.SubElement(mat_elem, "color", rgba=color)

    def _get_material_color(self, material: Material) -> str:
        name_lower = material.name.lower()
        for material_type, color in DEFAULT_COLORS.items():
            if material_type in name_lower:
                return color
        return DEFAULT_COLORS["default"]

    # ------------------------------------------------------------------
    # Single link
    # ------------------------------------------------------------------

    def _add_link(
        self,
        parent: etree._Element,
        body: Body,
        model: AssemblyModel,
        mesh_converter: MeshConverter,
    ) -> None:
        link = etree.SubElement(parent, "link", name=body.name)

        if body.inertia is not None:
            self._add_inertial(link, body)

        mesh_path = self._convert_mesh(body, mesh_converter)
        if mesh_path is not None:
            self._add_visual(link, body, mesh_path)
            self._add_collisions(link, body.name, mesh_path, mesh_converter)

    # ------------------------------------------------------------------
    # Rigid group link
    # ------------------------------------------------------------------

    def _add_rigid_group_link(
        self,
        parent: etree._Element,
        member_names: list[str],
        model: AssemblyModel,
        mesh_converter: MeshConverter,
    ) -> str:
        primary = model.get_body(member_names[0])
        if primary is None:
            return member_names[0]

        group_name = "_".join(member_names[:2]) + "_group"
        link = etree.SubElement(parent, "link", name=group_name)
        link.append(etree.Comment(f" Rigid group: {', '.join(member_names)} "))

        # Simplified inertial: sum of masses
        total_mass = 0.0
        for bname in member_names:
            b = model.get_body(bname)
            if b is not None and b.inertia is not None:
                total_mass += b.inertia.mass

        if total_mass > 0 and primary.inertia is not None:
            inertial = etree.SubElement(link, "inertial")
            com = primary.inertia.center_of_mass
            etree.SubElement(
                inertial, "origin",
                xyz=f"{com[0]:.6g} {com[1]:.6g} {com[2]:.6g}", rpy="0 0 0",
            )
            etree.SubElement(inertial, "mass", value=f"{total_mass:.6g}")

        # Visual + collision for each member
        for bname in member_names:
            b = model.get_body(bname)
            if b is None:
                continue
            mesh_path = self._convert_mesh(b, mesh_converter)
            if mesh_path is None:
                continue

            rel = b.transform.relative_to(primary.transform)
            xyz = _format_xyz(rel.position)
            rpy = _format_rpy(rel.rotation)

            # Visual
            visual = etree.SubElement(link, "visual")
            etree.SubElement(visual, "origin", xyz=xyz, rpy=rpy)
            geom = etree.SubElement(visual, "geometry")
            fname = str(mesh_path).replace("\\", "/")
            etree.SubElement(geom, "mesh", filename=fname, scale="0.001 0.001 0.001")
            if b.material_name:
                etree.SubElement(visual, "material", name=b.material_name)

            # Collision (convex parts if CoACD, else full mesh)
            for col_path in mesh_converter.get_collision_paths(bname):
                collision = etree.SubElement(link, "collision")
                etree.SubElement(collision, "origin", xyz=xyz, rpy=rpy)
                geom = etree.SubElement(collision, "geometry")
                col_fname = str(col_path).replace("\\", "/")
                etree.SubElement(
                    geom, "mesh", filename=col_fname, scale="0.001 0.001 0.001"
                )

        return group_name

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _convert_mesh(
        self, body: Body, mesh_converter: MeshConverter
    ) -> Optional[Path]:
        if body.geometry_file is None:
            return None
        try:
            return mesh_converter.convert(
                body.geometry_file, body.name, tolerance=self._mesh_tolerance,
            )
        except Exception as e:
            logger.warning("Failed to convert mesh for %s: %s", body.name, e)
            return None

    def _add_inertial(self, link: etree._Element, body: Body) -> None:
        if body.inertia is None:
            return
        inertial = etree.SubElement(link, "inertial")
        com = body.inertia.center_of_mass
        etree.SubElement(
            inertial, "origin",
            xyz=f"{com[0]:.6g} {com[1]:.6g} {com[2]:.6g}", rpy="0 0 0",
        )
        etree.SubElement(inertial, "mass", value=f"{body.inertia.mass:.6g}")
        I = body.inertia.inertia_tensor
        etree.SubElement(
            inertial, "inertia",
            ixx=f"{I[0,0]:.6g}", ixy=f"{I[0,1]:.6g}", ixz=f"{I[0,2]:.6g}",
            iyy=f"{I[1,1]:.6g}", iyz=f"{I[1,2]:.6g}", izz=f"{I[2,2]:.6g}",
        )

    def _add_visual(
        self, link: etree._Element, body: Body, mesh_path: Path
    ) -> None:
        visual = etree.SubElement(link, "visual")
        etree.SubElement(visual, "origin", xyz="0 0 0", rpy="0 0 0")
        geometry = etree.SubElement(visual, "geometry")
        fname = str(mesh_path).replace("\\", "/")
        etree.SubElement(geometry, "mesh", filename=fname, scale="0.001 0.001 0.001")
        if body.material_name:
            etree.SubElement(visual, "material", name=body.material_name)

    def _add_collisions(
        self,
        link: etree._Element,
        mesh_name: str,
        mesh_path: Path,
        mesh_converter: MeshConverter,
    ) -> None:
        for col_path in mesh_converter.get_collision_paths(mesh_name):
            collision = etree.SubElement(link, "collision")
            etree.SubElement(collision, "origin", xyz="0 0 0", rpy="0 0 0")
            geometry = etree.SubElement(collision, "geometry")
            fname = str(col_path).replace("\\", "/")
            etree.SubElement(
                geometry, "mesh", filename=fname, scale="0.001 0.001 0.001"
            )

    def _add_fixed_joint(
        self, parent: etree._Element, link_name: str, body: Body
    ) -> None:
        joint = etree.SubElement(
            parent, "joint", name=f"{link_name}_joint", type="fixed",
        )
        etree.SubElement(joint, "parent", link="base_link")
        etree.SubElement(joint, "child", link=link_name)

        pos = body.transform.position
        rpy = rotation_to_euler(
            body.transform.rotation, EulerConvention.URDF_RPY, degrees=False,
        )
        etree.SubElement(
            joint, "origin",
            xyz=f"{pos[0]:.6g} {pos[1]:.6g} {pos[2]:.6g}",
            rpy=f"{rpy[0]:.6g} {rpy[1]:.6g} {rpy[2]:.6g}",
        )
